[project]
name = "cron"
version = "1.0"
dependencies = ["beautifulsoup4"]
requires-python = ">=3.12"

[dependency-groups]
lint = ["pre-commit"]

[tool.ruff]
include = ["pyproject.toml", "scripts/**/*.py"]
line-length = 120
output-format = "concise"
target-version = "py312"

[tool.ruff.lint]
select = ["F", "E", "W", "B", "I", "PL", "RUF"]
ignore = ["E203","B005"]
