name: Chess Tournament Tracker

on:
  schedule:
    # On date 2,16 at 03:30 UTC (09:00 IST)
    - cron: "30 3 2,16 * *"
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: rsb-23/actions/checkout@main
        with:
          persist-credentials: true
      - uses: rsb-23/actions/setup-python@main

      - name: Run chess scraper
        run: |
          pip install .
          python scripts/fetch_chess.py

      - name: Commit and push changes
        uses: rsb-23/actions/commit-n-push@main
        with:
          git_user: "cron[bot]"
          files: "data/"
          commit_message: "data: update chess tournaments [no ci]"
